routes/web.php
<?php

/* Start Section Dashboard Routes  */

Route::group(['middleware' => ['web'], 'prefix' => 'admin', 'namespace' => 'Dashboard'], function () {

    Route::group(['middleware' => ['MustBeLoggedIn:web']], function () {

        # Dashboard Entry Point.
        Route::get('/', 'BackendIndexController@index')->name('adminHomePage');
        # Dashboard Entry Point.

        # Users Routes.
        Route::get('/users', 'Users\UserController@index')->name('users.index');
        Route::get('/users/{user_id}', 'Users\UserController@show')->name('users.show');
        # Users Routes.

        # Categories Routes.
        Route::get('/categories', 'Categories\CategoryController@index')->name('categories.index');
        Route::get('/categories/{category_id}', 'Categories\CategoryController@show')->name('categories.show_sub_categories');
        # Categories Routes.

        # Sellers Routes.
        Route::resource('sellers', 'Sellers\SellerController');
        # Sellers Routes.

        # Products Routes.
        Route::get('product/{image_id}/{image_name}/delete', 'Products\ProductController@deleteProductImage')->name('products.delete_image');
        Route::resource('products', 'Products\ProductController');
        # Products Routes.


        Route::resource('system-feedback', 'Feedback\FeedbackController')->only([
            'index', 'destroy'
        ]);

    });


    /* START ROUTING SECTION FOR AUTHENTICATION */

    Route::group(['namespace' => 'SystemAuthentication'], function () {
        Route::get('logout', 'AdminLogoutController@logout')->name('logout');
        Route::post('login', 'AdminLoginController@LoginToDashboard')->name('LoginToDashboard');
        Route::get('login', 'AdminLoginController@showAdminView')->name('loginView');
    });

    /* END ROUTING SECTION FOR AUTHENTICATION */
});

/* End Section Dashboard Routes  */


/* Start section Front-end Routes */

Route::group(['middleware' => ['web'], 'prefix' => '/', 'namespace' => 'FrontEnd'], function () {

    # Intro Page ( Home Page ).
    Route::get('/', 'FrontEndController@index')->name('frontend.home');

    # Start section routes user must be logged in to can access them.
    Route::group(['middleware' => ['MustBeLoggedIn:user']], function () {

        # User
        Route::post('user/review-product/{product_id}', 'Users\ReviewProductController@reviewProduct')->name('frontend.user.review-product');
        Route::get('user/system-feedback', 'Users\SystemFeedbackController@getSendFeedbackViewPage')->name('frontend.user.send-feedback-view');
        Route::post('user/system-feedback', 'Users\SystemFeedbackController@giveSystemFeedback')->name('frontend.user.send-feedback');
        # User

    });
    # End section routes user must be logged in to can access them.

    # Users
    Route::get('user', 'Users\UserController@getAccountView')->name('frontend.users.get-account-view'); // this page has view  for login and register.
    Route::post('user/register', 'Users\UserController@register')->name('frontend.users.register');
    Route::post('user/login', 'Users\UserController@login')->name('frontend.users.login');
    Route::post('user/logout', 'Users\UserController@logout')->name('frontend.users.logout');
    Route::get('user/update-profile', 'Users\UserController@GetUpdateProfileForm')->name('frontend.users.get-update-profile-form');
    Route::patch('user/update-profile', 'Users\UserController@updateUserProfile')->name('frontend.users.updateUserProfile');
    # Users

    # Products
    Route::get('products/comparison', 'Products\ProductComparison@getQueuedComparisonProducts')->name('frontend.products.get-comparison-view');
    Route::get('products/{product_id}', 'Products\ProductController@getProductDetails')->name('frontend.products.show');
    Route::post('products/{product_id}/add-to-compare', 'Products\ProductComparison@addProductToCompare')->name('frontend.products.add-to-compare');
    Route::post('products/clear-comparison-list', 'Products\ProductComparison@clearComparisonList')->name('frontend.products.clear-comparison-list');
    # Products

    # Categories
    Route::get('category/{category_id}/products', 'Products\ProductController@getProductByCategory')->name('frontend.get-products-by-category');
    # Categories
});

/* End section Front-end Routes */

app/Models/Seller.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Seller extends Model
{
    protected $table = 'sellers';

    protected $fillable = [
        'name',
        'summary',
        'address',
        'email_address',
        'phone_number',
    ];
}

app/Http/Controllers/Dashboard/BackendIndexController.php
<?php

namespace App\Http\Controllers\Dashboard;


class BackendIndexController
{
    /**
     * GET DASHBOARD HOME
     */
    public function index()
    {
        return view('Dashboard.index');
    }
}

app/Http/Controllers/Dashboard/Categories/CategoryController.php
<?php


namespace App\Http\Controllers\Dashboard\Categories;


use App\Models\Category;
use App\Models\SubCategories;
use Illuminate\Contracts\View\Factory;
use Illuminate\View\View;

class CategoryController
{

    /**
     * Get List of Available Categories
     */
    public function index()
    {
        // Make a query to get all categories.
        $categories = Category::get();

        // Return results to view to start render in the front-end
        return view('Dashboard.Categories.index', compact('categories'));
    }


    /**
     * Get list for all sub categories belongs to the given main Category id
     *
     * @param $category_id
     *
     * @return Factory|View
     */
    public function show($category_id)
    {
        // Make a query to get all sub categories that belong to given main category.
        $subCategories = SubCategories::where('category_id', $category_id)->get();

        // Return results to view to start render in the front-end
        return view('Dashboard.Categories.show', compact('subCategories'));
    }
}

app/Http/Controllers/Dashboard/Feedback/FeedbackController.php
<?php


namespace App\Http\Controllers\Dashboard\Feedback;


use App\Models\systemFeedback;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class FeedbackController
{
    /**
     * Get List of system feedback.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $feedback = systemFeedback::latest()->paginate();

        return view('Dashboard.Feedback.index', compact('feedback'));
    }

    /**
     * Delete a Feedback.
     *
     * @param $feedback_id
     *
     * @return RedirectResponse
     */
    public function destroy($feedback_id)
    {
        systemFeedback::findOrFail($feedback_id)->delete();

        return back()->with(['success' => 'Feedback has been deleted successfully!']);
    }
}

app/Http/Controllers/Dashboard/Products/ProductController.php
<?php


namespace App\Http\Controllers\Dashboard\Products;


use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\Seller;
use App\Models\SubCategories;
use App\Traits\FileUploader;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class ProductController
{
    use FileUploader;

    /**
     * Get List of Available Products
     */
    public function index()
    {
        // Make a query to get all Products.
        $products = Product::paginate(5);

        return view('Dashboard.Products.index', compact('products'));
    }


    /**
     * Get Create form view.
     *
     * @return Factory|View
     */
    public function create()
    {
        $categories = Category::get();
        $sellers = Seller::pluck('name', 'id');
        $categories = $this->formatCategoriesToOptGroupSelect($categories);

        return View('Dashboard.Products.create', compact('categories', 'sellers'));
    }


    /**
     * Get User Details.
     *
     * @param $product_id
     *
     * @return Factory|View
     */
    public function show($product_id)
    {
        $product = Product::findOrFail($product_id);
        $productAvgReviews = $product->reviews()->avg('rating');

        return view('Dashboard.Products.show', compact('product', 'productAvgReviews'));
    }


    /**
     * @param Request $request
     *
     * @return JsonResponse|RedirectResponse
     */
    public function store(Request $request)
    {
        // Validate Request
        $request->validate($this->getValidationsRules());

        // Merge Parent Category id with our request to save it with product details.
        $request->merge([
            'category_id' => SubCategories::where('id', $request->sub_category_id)->first()->category_id
        ]);

        // Create and Save Product in a Database.
        $product = Product::create($request->all());

        // Upload images And assign them to the product in a Database.
        $this->saveAndUploadProductImages($product, $request);

        $product->productSeller()->sync([
            $product->id => [
                'seller_id'  => $request->seller_id,
                'sell_price' => $request->sell_price
            ]
        ]);

        return redirect(route('products.index'))->with(['success' => 'Product Saved Successfully.']);
    }


    /**
     * Edit Product Information ( Get View Form to edit ).
     *
     * @param $id
     * @return Factory|View
     */
    public function edit($id)
    {
        // Make a Query to get Product by ID
        $product = Product::with('productSeller')->findOrFail($id);

        $categories = Category::get();
        $categories = $this->formatCategoriesToOptGroupSelect($categories);

        $sellers = Seller::pluck('name', 'id');

        return view('Dashboard.Products.edit', compact('product', 'categories', 'sellers'));
    }


    /**
     * Update Product information.
     *
     * @param Request $request
     *
     * @param $id
     *
     * @return RedirectResponse
     */
    public function update(Request $request, $id)
    {
        // Validate Request
        $request->validate($this->getValidationsRules('edit'));

        // Find by id or fails ( get 404 ) error
        $product = Product::findOrFail($id);

        // Merge Parent Category id with our request to save it with product details.
        $request->merge([
            'category_id' => SubCategories::where('id', $request->sub_category_id)->first()->category_id
        ]);

        // Update date
        $product->update($request->all());

        $product->productSeller()->sync([
            $product->id => [
                'seller_id'  => $request->seller_id,
                'sell_price' => $request->sell_price
            ]
        ]);

        // Upload images And assign them to the product in a Database.
        $this->saveAndUploadProductImages($product, $request);

        return redirect(route('products.index'))->with(['success' => 'Product Updated Successfully.']);
    }



    /**
     * @param $id
     *
     * @return JsonResponse|RedirectResponse
     */
    public function destroy($id)
    {
        // Make a Query to get Product by ID
        $product = Product::findOrFail($id);

        // Delete Images from Public Folder ( Uploads folder )
        foreach ($product->images as $image) {
           if (file_exists($file = public_path('/Uploads/Products/'.$image->image_path))) {
               unlink($file);
           }
        }
        // Delete Images from Public Folder ( Uploads folder )

        // Delete Product
        $product->delete();

        return redirect(route('products.index'))->with(['success' => 'Product Deleted Successfully.']);
    }

    /**
     * @param $categories
     *
     * @return array
     */
    public function formatCategoriesToOptGroupSelect($categories)
    {
        $results = [];

        /*
         *  We need format data to be as below ( to view it as opt group select ).
         *   "Mobiles" => [
                1 => "Apple"
                2 => "Samsung"
                3 => "Huawei"
              ],
              "Cameras" => [
                2 => "Cameras"
                4 => "Canon"
                5 => "Nikon"
                6 => "Panasonic"
              ]
         *
         * */

        foreach ($categories as $category) {

            $results[$category['name']][$category->id] = $category['name'];

            foreach ($category->subCategories as $subCategory) {
                $results[$category['name']][$subCategory->id] = $subCategory['name'];
            }
        }

        return $results;
    }


    /**
     * @param $product
     *
     * @param Request $request
     *
     * @return bool
     */
    public function saveAndUploadProductImages($product, Request $request)
    {
        // Start section Upload Images

        $imagesPaths = [];

        if ($request->hasFile('images')) {
            foreach($request->file('images') as $file) {
                $imagesPaths[] = $this->uploadFile($file, 'Products');
            }
        }

        // End section Upload Images

        // If we have images Save them to our Product.
        if ($imagesPaths) {
            // Assign the Uploaded image to this Product
            foreach($imagesPaths as $file) {
                $product->images()->create([
                    'image_path' => $file
                ]);
            }
        }

        return true;
    }


    /**
     * Delete Product Image by name and id
     *
     * @param $image_id
     *
     * @param $image_name
     *
     * @return RedirectResponse
     */
    public function deleteProductImage($image_id, $image_name)
    {
        $isDeleted = ProductImage::where(['id' => $image_id, 'image_path' => $image_name,])->delete();

        if ($isDeleted) {
            return back()->with(['info' => 'Image was deleted successfully.']);
        }

        return back();
    }


    /**
     * Get Product Validations rules.
     *
     * @param string $type
     * @return array
     */
    public function getValidationsRules($type = 'add'): array
    {
        return [
            'name' => 'required|max:255',
            'description' => 'required',
            'sub_category_id' => 'required|exists:sub_categories,id',
            'seller_id' => 'required|exists:sellers,id',
            'images' => $type == ('add') ? 'required|array|min:1' : '',
            'images.*' => $type == ('add') ? 'required|image|max:1024' : '' // must be Valid image and max size is 1 MB.
        ];
    }
}

app/Http/Controllers/Dashboard/Sellers/SellerController.php
<?php


namespace App\Http\Controllers\Dashboard\Sellers;


use App\Models\Seller;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class SellerController
{
    /**
     * Get List of Available Sellers
     */
    public function index()
    {
        // Make a query to get all Sellers.
        $sellers = Seller::paginate(5);

        return view('Dashboard.Sellers.index', compact('sellers'));
    }


    /**
     * Get
     *
     * @return Factory|View
     */
    public function create()
    {
        return View('Dashboard.Sellers.create');
    }


    /**
     * @param Request $request
     *
     * @return JsonResponse|RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'           => 'required|max:255',
            'summary'        => 'required|max:500',
            'address'        => 'required|max:500',
            'email_address'  => 'required|email',
            'phone_number'   => 'required',
        ]);

        Seller::create($request->all());

        return redirect(route('sellers.index'))->with([
            'success' => 'Seller information Saved Successfully.'
        ]);
    }


    /**
     * Edit Seller Information ( Get View Form to edit ).
     *
     * @param $id
     * @return Factory|View
     */
    public function edit($id)
    {


        // Make a Query to get seller by ID
        $seller = Seller::findOrFail($id);

        return view('Dashboard.Sellers.edit', compact('seller'));
    }


    /**
     * Update Seller information.
     *
     * @param Request $request
     *
     * @param $id
     *
     * @return RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'           => 'required|max:255',
            'summary'        => 'required|max:500',
            'address'        => 'required|max:500',
            'email_address'  => 'required|email',
            'phone_number'   => 'required',
        ]);

        // Find by id or fails ( get 404 ) error
        $seller = Seller::findOrFail($id);

        // update date
        $seller->update($request->all());

        return redirect(route('sellers.index'))->with([
            'success' => 'Seller information Updated Successfully.'
        ]);
    }

    /**
     * @param $id
     *
     * @return JsonResponse|RedirectResponse
     */
    public function destroy($id)
    {
        $seller = Seller::findOrFail($id);
        $seller->delete();

        return redirect(route('sellers.index'))->with([
            'success' => 'Seller information Deleted Successfully.'
        ]);
    }
}

app/Http/Controllers/Dashboard/SystemAuthentication/AdminLogoutController.php
<?php

namespace App\Http\Controllers\Dashboard\SystemAuthentication;

use App\Http\Controllers\Controller;

class AdminLogoutController extends Controller
{
    /* LOGOUT ADMIN */
    public function logout()
    {
        if (auth('web')->check()) {
            auth('web')->logout();
        }

        return redirect(route('loginView')) ;
    }
}

resources/views/Dashboard/Sellers/_form.blade.php
<div class="form-group">
    Seller Name
    {!! Form::text('name', null, ['class' => 'form-control', 'autocomplete' => 'nope']) !!}
</div>

<div class="form-group">
    Phone Number
    {!! Form::text('phone_number', null, ['class' => 'form-control', 'autocomplete' => 'nope']) !!}
</div>

<div class="form-group">
    Email Address
    {!! Form::email('email_address', null, ['class' => 'form-control','placeholder' => 'eg: foo@bar.com','autocomplete'=>'nope']) !!}
</div>

<div class="form-group">
    Summary
    {!! Form::textarea('summary', null, ['class' => 'form-control', 'autocomplete' => 'nope', 'rows' => '2']) !!}
</div>

<div class="form-group">
    <label> Address</label>
    {!! Form::textarea('address', null, ['class' => 'form-control', 'autocomplete' => 'nope', 'rows' => '2']) !!}
</div>

<button type="submit" class="btn btn-primary">
    <i class="fa fa-save"></i>
    Save Data
</button>

<a href="{{route('sellers.index')}}" type="button" class="btn btn-warning">
    <i class="fa fa-times-circle"></i> Cancel
</a>

resources/views/Dashboard/Sellers/create.blade.php
@extends('Dashboard.Layouts.Layout')
@section('page-name', 'Seller Information')

@section('content')

    <div class="row">
        <div class="col-md-12 col-md-auto">
            <div class="portlet light bordered">
                <div class="col-md-10">
                    {!! Form::open(['action'=> "Dashboard\Sellers\SellerController@store", 'class' => 'form-horizontal', 'files' => true]) !!}
                        @include('Dashboard.Sellers._form', ['action_title' => 'Add', 'type' =>'add'])
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/Dashboard/Sellers/edit.blade.php
@extends('Dashboard.Layouts.Layout')
@section('title', $title ?? __('system.edit'))

@section('content')

    @stack('breadcrumb')

    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-body form">
                    <div role="form">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-10">
                                    {!! Form::model($seller, ['method' => 'PATCH', 'action' => ["Dashboard\Sellers\SellerController@update", $seller->id], 'class' => 'form-horizontal','files' => true]) !!}
                                    @include('Dashboard.Sellers._form', ['text' => __('system.edit'), 'actionTitle' => __('system.edit') , 'type' => 'edit'])
                                    {!! Form::close() !!}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/Dashboard/Sellers/index.blade.php
@extends('Dashboard.Layouts.Layout')
@section('page-name', 'Sellers Information')
@section('content')

    <div class="row">
        <div class="container-lg">
            <div class="buttons-actions">
                <a class="btn btn-primary btn-circle btn-sm" href="{{ route('sellers.create') }}">
                    <i class="fa fa-plus"></i>
                    Add New
                </a>

            </div>
            <br>
            <div class="panel-body">

                @if($sellers->isNotEmpty())
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th># ID</th>
                            <th>Name </th>
                            <th>Summary</th>
                            <th>address</th>
                            <th>Email</th>
                            <th>Phone Number</th>
                            <th> Options </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($sellers as $seller)
                            <tr>
                                <td>{{ $seller->id }}</td>
                                <td title="{{ $seller->name }}"> {{ $seller->name }} </td>
                                <td title="{{ $seller->summary }}"> {{ $seller->summary }} </td>
                                <td>{{ $seller->address }}</td>
                                <td>{{ $seller->email_address }}</td>
                                <td>{{ $seller->phone_number }}</td>
                                <td>
                                    {!! Form::open(['method' => 'DELETE', 'action' => ['Dashboard\Sellers\SellerController@destroy', $seller->id]]) !!}

                                    <a href="{{ Url('/') }}/admin/sellers/{{ $seller->id }}/edit" class="btn btn-info btn-sm"> <i class="fa fa-edit"></i>
                                    </a>
                                    {!! Form::submit('Delete', ['class'=>'btn btn-danger btn-sm btn-circle', 'onclick' => "return confirm('هل متأكد من الحذف ؟');"] ) !!}

                                    {!! Form::close() !!}
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $sellers->links() }}
                @else
                    <div class="alert alert-info">There's no data to show.</div>
                @endif
            </div>
        </div>
    </div>

    <!-- END PAGE LEVEL PLUGINS -->
@endsection