routes/web.php
<?php

/* Start Section Dashboard Routes  */

Route::group(['middleware' => ['web'], 'prefix' => 'admin', 'namespace' => 'Dashboard'], function () {

    Route::group(['middleware' => ['MustBeLoggedIn:web']], function () {

        # Dashboard Entry Point.
        Route::get('/', 'BackendIndexController@index')->name('adminHomePage');
        # Dashboard Entry Point.

        # Users Routes.
        Route::get('/users', 'Users\UserController@index')->name('users.index');
        Route::get('/users/{user_id}', 'Users\UserController@show')->name('users.show');
        # Users Routes.

        # Categories Routes.
        Route::get('/categories', 'Categories\CategoryController@index')->name('categories.index');
        Route::get('/categories/{category_id}', 'Categories\CategoryController@show')->name('categories.show_sub_categories');
        # Categories Routes.

        # Sellers Routes.
        Route::resource('sellers', 'Sellers\SellerController');
        # Sellers Routes.

        # Products Routes.
        Route::get('product/{image_id}/{image_name}/delete', 'Products\ProductController@deleteProductImage')->name('products.delete_image');
        Route::resource('products', 'Products\ProductController');
        # Products Routes.


        Route::resource('system-feedback', 'Feedback\FeedbackController')->only([
            'index', 'destroy'
        ]);

    });


    /* START ROUTING SECTION FOR AUTHENTICATION */

    Route::group(['namespace' => 'SystemAuthentication'], function () {
        Route::get('logout', 'AdminLogoutController@logout')->name('logout');
        Route::post('login', 'AdminLoginController@LoginToDashboard')->name('LoginToDashboard');
        Route::get('login', 'AdminLoginController@showAdminView')->name('loginView');
    });

    /* END ROUTING SECTION FOR AUTHENTICATION */
});

/* End Section Dashboard Routes  */


/* Start section Front-end Routes */

Route::group(['middleware' => ['web'], 'prefix' => '/', 'namespace' => 'FrontEnd'], function () {

    # Intro Page ( Home Page ).
    Route::get('/', 'FrontEndController@index')->name('frontend.home');

    # Start section routes user must be logged in to can access them.
    Route::group(['middleware' => ['MustBeLoggedIn:user']], function () {

        # User
        Route::post('user/review-product/{product_id}', 'Users\ReviewProductController@reviewProduct')->name('frontend.user.review-product');
        Route::get('user/system-feedback', 'Users\SystemFeedbackController@getSendFeedbackViewPage')->name('frontend.user.send-feedback-view');
        Route::post('user/system-feedback', 'Users\SystemFeedbackController@giveSystemFeedback')->name('frontend.user.send-feedback');
        # User

    });
    # End section routes user must be logged in to can access them.

    # Users
    Route::get('user', 'Users\UserController@getAccountView')->name('frontend.users.get-account-view'); // this page has view  for login and register.
    Route::post('user/register', 'Users\UserController@register')->name('frontend.users.register');
    Route::post('user/login', 'Users\UserController@login')->name('frontend.users.login');
    Route::post('user/logout', 'Users\UserController@logout')->name('frontend.users.logout');
    Route::get('user/update-profile', 'Users\UserController@GetUpdateProfileForm')->name('frontend.users.get-update-profile-form');
    Route::patch('user/update-profile', 'Users\UserController@updateUserProfile')->name('frontend.users.updateUserProfile');
    # Users

    # Products
    Route::get('products/comparison', 'Products\ProductComparison@getQueuedComparisonProducts')->name('frontend.products.get-comparison-view');
    Route::get('products/{product_id}', 'Products\ProductController@getProductDetails')->name('frontend.products.show');
    Route::post('products/{product_id}/add-to-compare', 'Products\ProductComparison@addProductToCompare')->name('frontend.products.add-to-compare');
    Route::post('products/clear-comparison-list', 'Products\ProductComparison@clearComparisonList')->name('frontend.products.clear-comparison-list');
    # Products

    # Categories
    Route::get('category/{category_id}/products', 'Products\ProductController@getProductByCategory')->name('frontend.get-products-by-category');
    # Categories
});

/* End section Front-end Routes */

app/Http/Controllers/Dashboard/BackendIndexController.php
<?php

namespace App\Http\Controllers\Dashboard;


class BackendIndexController
{
    /**
     * GET DASHBOARD HOME
     */
    public function index()
    {
        return view('Dashboard.index');
    }
}

app/Http/Controllers/Dashboard/Categories/CategoryController.php
<?php


namespace App\Http\Controllers\Dashboard\Categories;


use App\Models\Category;
use App\Models\SubCategories;
use Illuminate\Contracts\View\Factory;
use Illuminate\View\View;

class CategoryController
{

    /**
     * Get List of Available Categories
     */
    public function index()
    {
        // Make a query to get all categories.
        $categories = Category::get();

        // Return results to view to start render in the front-end
        return view('Dashboard.Categories.index', compact('categories'));
    }


    /**
     * Get list for all sub categories belongs to the given main Category id
     *
     * @param $category_id
     *
     * @return Factory|View
     */
    public function show($category_id)
    {
        // Make a query to get all sub categories that belong to given main category.
        $subCategories = SubCategories::where('category_id', $category_id)->get();

        // Return results to view to start render in the front-end
        return view('Dashboard.Categories.show', compact('subCategories'));
    }
}

app/Http/Controllers/Dashboard/Feedback/FeedbackController.php
<?php


namespace App\Http\Controllers\Dashboard\Feedback;


use App\Models\systemFeedback;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class FeedbackController
{
    /**
     * Get List of system feedback.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $feedback = systemFeedback::latest()->paginate();

        return view('Dashboard.Feedback.index', compact('feedback'));
    }

    /**
     * Delete a Feedback.
     *
     * @param $feedback_id
     *
     * @return RedirectResponse
     */
    public function destroy($feedback_id)
    {
        systemFeedback::findOrFail($feedback_id)->delete();

        return back()->with(['success' => 'Feedback has been deleted successfully!']);
    }
}

app/Http/Controllers/Dashboard/Products/ProductController.php
<?php


namespace App\Http\Controllers\Dashboard\Products;


use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\Seller;
use App\Models\SubCategories;
use App\Traits\FileUploader;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class ProductController
{
    use FileUploader;

    /**
     * Get List of Available Products
     */
    public function index()
    {
        // Make a query to get all Products.
        $products = Product::paginate(5);

        return view('Dashboard.Products.index', compact('products'));
    }


    /**
     * Get Create form view.
     *
     * @return Factory|View
     */
    public function create()
    {
        $categories = Category::get();
        $sellers = Seller::pluck('name', 'id');
        $categories = $this->formatCategoriesToOptGroupSelect($categories);

        return View('Dashboard.Products.create', compact('categories', 'sellers'));
    }


    /**
     * Get User Details.
     *
     * @param $product_id
     *
     * @return Factory|View
     */
    public function show($product_id)
    {
        $product = Product::findOrFail($product_id);
        $productAvgReviews = $product->reviews()->avg('rating');

        return view('Dashboard.Products.show', compact('product', 'productAvgReviews'));
    }


    /**
     * @param Request $request
     *
     * @return JsonResponse|RedirectResponse
     */
    public function store(Request $request)
    {
        // Validate Request
        $request->validate($this->getValidationsRules());

        // Merge Parent Category id with our request to save it with product details.
        $request->merge([
            'category_id' => SubCategories::where('id', $request->sub_category_id)->first()->category_id
        ]);

        // Create and Save Product in a Database.
        $product = Product::create($request->all());

        // Upload images And assign them to the product in a Database.
        $this->saveAndUploadProductImages($product, $request);

        $product->productSeller()->sync([
            $product->id => [
                'seller_id'  => $request->seller_id,
                'sell_price' => $request->sell_price
            ]
        ]);

        return redirect(route('products.index'))->with(['success' => 'Product Saved Successfully.']);
    }


    /**
     * Edit Product Information ( Get View Form to edit ).
     *
     * @param $id
     * @return Factory|View
     */
    public function edit($id)
    {
        // Make a Query to get Product by ID
        $product = Product::with('productSeller')->findOrFail($id);

        $categories = Category::get();
        $categories = $this->formatCategoriesToOptGroupSelect($categories);

        $sellers = Seller::pluck('name', 'id');

        return view('Dashboard.Products.edit', compact('product', 'categories', 'sellers'));
    }


    /**
     * Update Product information.
     *
     * @param Request $request
     *
     * @param $id
     *
     * @return RedirectResponse
     */
    public function update(Request $request, $id)
    {
        // Validate Request
        $request->validate($this->getValidationsRules('edit'));

        // Find by id or fails ( get 404 ) error
        $product = Product::findOrFail($id);

        // Merge Parent Category id with our request to save it with product details.
        $request->merge([
            'category_id' => SubCategories::where('id', $request->sub_category_id)->first()->category_id
        ]);

        // Update date
        $product->update($request->all());

        $product->productSeller()->sync([
            $product->id => [
                'seller_id'  => $request->seller_id,
                'sell_price' => $request->sell_price
            ]
        ]);

        // Upload images And assign them to the product in a Database.
        $this->saveAndUploadProductImages($product, $request);

        return redirect(route('products.index'))->with(['success' => 'Product Updated Successfully.']);
    }



    /**
     * @param $id
     *
     * @return JsonResponse|RedirectResponse
     */
    public function destroy($id)
    {
        // Make a Query to get Product by ID
        $product = Product::findOrFail($id);

        // Delete Images from Public Folder ( Uploads folder )
        foreach ($product->images as $image) {
           if (file_exists($file = public_path('/Uploads/Products/'.$image->image_path))) {
               unlink($file);
           }
        }
        // Delete Images from Public Folder ( Uploads folder )

        // Delete Product
        $product->delete();

        return redirect(route('products.index'))->with(['success' => 'Product Deleted Successfully.']);
    }

    /**
     * @param $categories
     *
     * @return array
     */
    public function formatCategoriesToOptGroupSelect($categories)
    {
        $results = [];

        /*
         *  We need format data to be as below ( to view it as opt group select ).
         *   "Mobiles" => [
                1 => "Apple"
                2 => "Samsung"
                3 => "Huawei"
              ],
              "Cameras" => [
                2 => "Cameras"
                4 => "Canon"
                5 => "Nikon"
                6 => "Panasonic"
              ]
         *
         * */

        foreach ($categories as $category) {

            $results[$category['name']][$category->id] = $category['name'];

            foreach ($category->subCategories as $subCategory) {
                $results[$category['name']][$subCategory->id] = $subCategory['name'];
            }
        }

        return $results;
    }


    /**
     * @param $product
     *
     * @param Request $request
     *
     * @return bool
     */
    public function saveAndUploadProductImages($product, Request $request)
    {
        // Start section Upload Images

        $imagesPaths = [];

        if ($request->hasFile('images')) {
            foreach($request->file('images') as $file) {
                $imagesPaths[] = $this->uploadFile($file, 'Products');
            }
        }

        // End section Upload Images

        // If we have images Save them to our Product.
        if ($imagesPaths) {
            // Assign the Uploaded image to this Product
            foreach($imagesPaths as $file) {
                $product->images()->create([
                    'image_path' => $file
                ]);
            }
        }

        return true;
    }


    /**
     * Delete Product Image by name and id
     *
     * @param $image_id
     *
     * @param $image_name
     *
     * @return RedirectResponse
     */
    public function deleteProductImage($image_id, $image_name)
    {
        $isDeleted = ProductImage::where(['id' => $image_id, 'image_path' => $image_name,])->delete();

        if ($isDeleted) {
            return back()->with(['info' => 'Image was deleted successfully.']);
        }

        return back();
    }


    /**
     * Get Product Validations rules.
     *
     * @param string $type
     * @return array
     */
    public function getValidationsRules($type = 'add'): array
    {
        return [
            'name' => 'required|max:255',
            'description' => 'required',
            'sub_category_id' => 'required|exists:sub_categories,id',
            'seller_id' => 'required|exists:sellers,id',
            'images' => $type == ('add') ? 'required|array|min:1' : '',
            'images.*' => $type == ('add') ? 'required|image|max:1024' : '' // must be Valid image and max size is 1 MB.
        ];
    }
}

app/Http/Controllers/Dashboard/Sellers/SellerController.php
<?php


namespace App\Http\Controllers\Dashboard\Sellers;


use App\Models\Seller;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class SellerController
{
    /**
     * Get List of Available Sellers
     */
    public function index()
    {
        // Make a query to get all Sellers.
        $sellers = Seller::paginate(5);

        return view('Dashboard.Sellers.index', compact('sellers'));
    }


    /**
     * Get
     *
     * @return Factory|View
     */
    public function create()
    {
        return View('Dashboard.Sellers.create');
    }


    /**
     * @param Request $request
     *
     * @return JsonResponse|RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'           => 'required|max:255',
            'summary'        => 'required|max:500',
            'address'        => 'required|max:500',
            'email_address'  => 'required|email',
            'phone_number'   => 'required',
        ]);

        Seller::create($request->all());

        return redirect(route('sellers.index'))->with([
            'success' => 'Seller information Saved Successfully.'
        ]);
    }


    /**
     * Edit Seller Information ( Get View Form to edit ).
     *
     * @param $id
     * @return Factory|View
     */
    public function edit($id)
    {


        // Make a Query to get seller by ID
        $seller = Seller::findOrFail($id);

        return view('Dashboard.Sellers.edit', compact('seller'));
    }


    /**
     * Update Seller information.
     *
     * @param Request $request
     *
     * @param $id
     *
     * @return RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'           => 'required|max:255',
            'summary'        => 'required|max:500',
            'address'        => 'required|max:500',
            'email_address'  => 'required|email',
            'phone_number'   => 'required',
        ]);

        // Find by id or fails ( get 404 ) error
        $seller = Seller::findOrFail($id);

        // update date
        $seller->update($request->all());

        return redirect(route('sellers.index'))->with([
            'success' => 'Seller information Updated Successfully.'
        ]);
    }

    /**
     * @param $id
     *
     * @return JsonResponse|RedirectResponse
     */
    public function destroy($id)
    {
        $seller = Seller::findOrFail($id);
        $seller->delete();

        return redirect(route('sellers.index'))->with([
            'success' => 'Seller information Deleted Successfully.'
        ]);
    }
}

app/Http/Controllers/Dashboard/SystemAuthentication/AdminLogoutController.php
<?php

namespace App\Http\Controllers\Dashboard\SystemAuthentication;

use App\Http\Controllers\Controller;

class AdminLogoutController extends Controller
{
    /* LOGOUT ADMIN */
    public function logout()
    {
        if (auth('web')->check()) {
            auth('web')->logout();
        }

        return redirect(route('loginView')) ;
    }
}

resources/views/Dashboard/Layouts/Footer.blade.php
<!-- jQuery -->
<script src="{{ Url('Dashboard') }}/plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ Url('Dashboard') }}/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{ Url('Dashboard') }}/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- ChartJS -->
<script src="{{ Url('Dashboard') }}/plugins/chart.js/Chart.min.js"></script>
<!-- Sparkline -->
<script src="{{ Url('Dashboard') }}/plugins/sparklines/sparkline.js"></script>
<!-- JQVMap -->
<script src="{{ Url('Dashboard') }}/plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="{{ Url('Dashboard') }}/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="{{ Url('Dashboard') }}/plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="{{ Url('Dashboard') }}/plugins/moment/moment.min.js"></script>
<script src="{{ Url('Dashboard') }}/plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ Url('Dashboard') }}/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="{{ Url('Dashboard') }}/plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="{{ Url('Dashboard') }}/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="{{ Url('Dashboard') }}/js/adminlte.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ Url('Dashboard') }}/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ Url('Dashboard') }}/js/demo.js"></script>

resources/views/Dashboard/Layouts/Header.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@yield('page-name') | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ Url('Dashboard') }}/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="{{ Url('Dashboard') }}/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{ Url('Dashboard') }}/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{{ Url('Dashboard') }}/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ Url('Dashboard') }}/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{ Url('Dashboard') }}/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{ Url('Dashboard') }}/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="{{ Url('Dashboard') }}/plugins/summernote/summernote-bs4.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

resources/views/Dashboard/Layouts/Layout.blade.php
<!DOCTYPE html>
<html>

@include('Dashboard.Layouts.Header')

<body class="hold-transition sidebar-mini layout-fixed">

<!-- ./wrapper -->
<div class="wrapper">

    <!-- Nav -->
@include('Dashboard.Layouts.Nav')
<!-- /.nav -->

    <!-- Main Sidebar Container -->
@include('Dashboard.Layouts.Sidebar')

<!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">
                            @yield('page-name')
                        </h1>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Main row -->
                <div class="row">
                    <!-- Left col -->
                    <section class="col-lg-12 connectedSortable">

                        <!-- Load Messenger Handler -->
                            @include('Partial.messenger')

                        @yield('content')
                    </section>
                    <!-- /.Left col -->
                </div>
                <!-- /.row (main row) -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>

    <!-- /.content-wrapper -->
    @include('Dashboard.Layouts.Main-Footer')
</div>
<!-- ./wrapper -->

@include('Dashboard.Layouts.Footer')

</body>
</html>

resources/views/Dashboard/Layouts/Main-Footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2020
        <a href="#"></a>
    </strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 1.0
    </div>
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->

resources/views/Dashboard/Layouts/Sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="{{Url('Dashboard')}}/img/AdminLTELogo.png" alt="Pricna Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">
            Pricena
        </span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{Url('Dashboard')}}/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">
                    @auth()
                        {{ auth('web')->user()->name }}
                    @endauth
                </a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                <li class="nav-item">
                    <a href="{{ route('adminHomePage') }}" class="nav-link {{ \Request::is('admin') ? 'active' : '' }}">
                        <p>
                            <i class="fa fa-home"></i>
                            Home Page
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('products.index') }}" class="nav-link {{ \Request::is('products') ? 'active' : '' }}">
                        <p>
                            <i class="fa fa-list-ol"></i>
                            Products
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('users.index') }}" class="nav-link {{ \Request::is('users') ? 'active' : '' }}">
                        <p>
                            <i class="fa fa-users"></i>
                            Users
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('system-feedback.index') }}" class="nav-link {{ \Request::is('feedback') ? 'active' : '' }}">
                        <p>
                            <i class="fa fa-vote-yea"></i>
                            System Feedback
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('sellers.index') }}" class="nav-link {{ \Request::is('Sellers') ? 'active' : '' }}">
                        <p>
                            <i class="fa fa-users-cog"></i>
                            Sellers
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('categories.index') }}" class="nav-link {{ \Request::is('categories') ? 'active' : '' }}">
                        <p>
                            <i class="fa fa-users-cog"></i>
                            Categories
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ route('logout') }}" class="nav-link">
                        <p>
                            <i class="fa fa-sign-out-alt"></i>
                            Logout
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>